name: I'm The Captain Now
keywords: [captain, now, look at me, captain phillips]
example: ["Look at me", "I'm the captain now"]
text:
  - anchor_x: 0.0
    anchor_y: 0.0
    scale_x: 1.0
    scale_y: 0.2
    alignment: center
    color: white
    stroke_color: black
    stroke_width: 2
    style: upper
    max_font_size: 60
  - anchor_x: 0.0
    anchor_y: 0.8
    scale_x: 1.0
    scale_y: 0.2
    alignment: center
    color: white
    stroke_color: black
    stroke_width: 2
    style: upper
    max_font_size: 60
