name: Trade Offer
keywords: [trade offer, i receive, you receive, tiktok]
example: ["I receive:", "You receive:", "Nothing"]
text:
  - anchor_x: 0.0
    anchor_y: 0.3
    scale_x: 0.5
    scale_y: 0.3
    alignment: center
    color: white
    stroke_color: black
    stroke_width: 2
    style: none
    max_font_size: 35
  - anchor_x: 0.5
    anchor_y: 0.3
    scale_x: 0.5
    scale_y: 0.3
    alignment: center
    color: white
    stroke_color: black
    stroke_width: 2
    style: none
    max_font_size: 35
  - anchor_x: 0.0
    anchor_y: 0.8
    scale_x: 1.0
    scale_y: 0.2
    alignment: center
    color: white
    stroke_color: black
    stroke_width: 2
    style: none
    max_font_size: 35
