name: Say The Line Bart
keywords: [say the line, bart, simpsons, sigh]
example: ["Say the line!", "Something overused", "Crowd cheers"]
text:
  - anchor_x: 0.0
    anchor_y: 0.0
    scale_x: 1.0
    scale_y: 0.15
    alignment: center
    color: white
    stroke_color: black
    stroke_width: 2
    style: none
    max_font_size: 30
  - anchor_x: 0.0
    anchor_y: 0.35
    scale_x: 1.0
    scale_y: 0.15
    alignment: center
    color: white
    stroke_color: black
    stroke_width: 2
    style: none
    max_font_size: 30
  - anchor_x: 0.0
    anchor_y: 0.75
    scale_x: 1.0
    scale_y: 0.15
    alignment: center
    color: white
    stroke_color: black
    stroke_width: 2
    style: none
    max_font_size: 30
