name: UNO Draw 25
keywords: [uno, draw 25, or, cards]
example: ["Admit you're wrong", "Draw 25 cards"]
text:
  - anchor_x: 0.0
    anchor_y: 0.0
    scale_x: 0.55
    scale_y: 0.4
    alignment: center
    color: black
    stroke_color: white
    stroke_width: 0
    style: none
    max_font_size: 40
  - anchor_x: 0.0
    anchor_y: 0.8
    scale_x: 1.0
    scale_y: 0.2
    alignment: center
    style: upper
    max_font_size: 60
