name: Domino Effect
keywords: [domino, effect, small thing, big consequence, chain reaction]
example: ["Small thing", "Huge consequence"]
text:
  - anchor_x: 0.0
    anchor_y: 0.0
    scale_x: 0.3
    scale_y: 0.5
    alignment: center
    color: white
    stroke_color: black
    stroke_width: 2
    style: none
    max_font_size: 25
  - anchor_x: 0.6
    anchor_y: 0.0
    scale_x: 0.4
    scale_y: 0.5
    alignment: center
    color: white
    stroke_color: black
    stroke_width: 2
    style: none
    max_font_size: 30
