name: Two Buttons
keywords: [two buttons, choice, decision, sweating]
example: ["Option A", "Option B"]
text:
  - anchor_x: 0.05
    anchor_y: 0.05
    scale_x: 0.4
    scale_y: 0.25
    alignment: center
    style: none
    max_font_size: 40
  - anchor_x: 0.42
    anchor_y: 0.05
    scale_x: 0.4
    scale_y: 0.25
    alignment: center
    style: none
    max_font_size: 40
