name: Soldier Protecting Sleeping Child
keywords: [soldier, protecting, sleeping, child, guardian]
example: ["Protector", "Protected thing", "Threat"]
text:
  - anchor_x: 0.0
    anchor_y: 0.0
    scale_x: 0.5
    scale_y: 0.3
    alignment: center
    color: white
    stroke_color: black
    stroke_width: 3
    style: none
    max_font_size: 30
  - anchor_x: 0.5
    anchor_y: 0.5
    scale_x: 0.5
    scale_y: 0.3
    alignment: center
    color: white
    stroke_color: black
    stroke_width: 3
    style: none
    max_font_size: 30
  - anchor_x: 0.0
    anchor_y: 0.5
    scale_x: 0.4
    scale_y: 0.3
    alignment: center
    color: white
    stroke_color: black
    stroke_width: 3
    style: none
    max_font_size: 30
